<?php
return [
    ['/vendor/jquery-1.12.4.min.js'],
    ['/bootstrap.min.js'],
    ['/wow.min.js'],
    ['/jquery-price-slider.js'],
    ['/jquery.meanmenu.js'],
    ['/owl.carousel.min.js'],
    ['/jquery.sticky.js'],
    ['/jquery.scrollUp.min.js'],
    ['/counterup/jquery.counterup.min.js'],
    ['/counterup/waypoints.min.js'],
    ['/counterup/counterup-active.js'],
    ['/scrollbar/jquery.mCustomScrollbar.concat.min.js'],
    ['/scrollbar/mCustomScrollbar-active.js'],
    ['/metisMenu/metisMenu.min.js'],
    ['/metisMenu/metisMenu-active.js'],
//    ['/morrisjs/raphael-min.js'],
//    ['/morrisjs/morris.js'],
//    ['/morrisjs/morris-active.js'],
    ['/sparkline/jquery.sparkline.min.js'],
    ['/sparkline/jquery.charts-sparkline.js'],
    ['/sparkline/sparkline-active.js'],
    ['/calendar/moment.min.js'],
    ['/calendar/fullcalendar.min.js'],
    ['/calendar/fullcalendar-active.js'],
    ['/plugins.js'],
    ['/main.js'],
//    ['/tawk-chat.js'],
];